name: "PR AI Review"
description: "Analyze PR diffs with OpenAI and post inline review comments"

inputs:
  openai_api_key:
    description: "OpenAI API key"
    required: true
  openai_model:
    description: "OpenAI model name"
    required: false
    default: "gpt-4o-mini"
  diff_chunk_size:
    description: "Max characters per diff chunk"
    required: false
    default: "12000"
  review_prompt:
    description: "Override default review prompt"
    required: false

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install deps
      shell: bash
      run: |
        npm install --no-audit --no-fund
        echo "Dependencies installed successfully"
        echo "Verifying package.json:"
        cat package.json
        echo "Available scripts:"
        npm run

    - name: Run PR review bot
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
        OPENAI_API_KEY: ${{ inputs.openai_api_key }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        INPUT_PR_NUMBER: ${{ github.event.pull_request.number }}
        OPENAI_MODEL: ${{ inputs.openai_model }}
        DIFF_CHUNK_SIZE: ${{ inputs.diff_chunk_size }}
        REVIEW_PROMPT: ${{ inputs.review_prompt }}
      run: |
        echo "Starting PR review bot..."
        echo "Node version: $(node --version)"
        echo "NPM version: $(npm --version)"
        echo "Current directory: $(pwd)"
        echo "Files in current directory: $(ls -la)"
        echo "Package.json contents:"
        cat package.json
        echo "Available scripts:"
        npm run
        echo "Running the bot directly:"
        node src/index.js


